### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by hugovanversendaal** [Meitinger/GraphSPARQL#3]
Hi,

According to the README, ordinary introspection is disabled. Is there anyway to enable introspection for development purposes?

Kind regards,
Hugo

**Comment by meitinger** [comment]
While there is no configurable setting, a minor change to line https://github.com/meitinger/GraphSPARQL/blob/54f372aa072a40bc9df33a8f3994276b9d0eb8df/src/Types/Schema.cs#L374 should re-enable all introspection types:
```c#
IGraphType? ISchema.FindType(string name) => _lookup.Value[name];
```

**Comment by hugovanversendaal** [comment]
Yes, that works. Thank you!

I really like GraphSPARQL by the way, it has a lot of great features. Thanks again!

**Comment by meitinger** [comment]
Glad to hear that, thanks :)
